// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repositories

import (
	"time"
)

type Genre struct {
	ID    int64
	Title string
}

type Movie struct {
	ID          int64
	Title       string
	Description string
	ReleaseYear int64
	Director    string
	Rating      int64
	IsWatched   bool
	TrailerUrl  string
	PosterUrl   string
}

type MoviesGenre struct {
	MovieID int64
	GenreID int64
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
}

type Watchlist struct {
	MovieID int64
	AddedAt time.Time
}
