// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: movies_genres.sql

package repositories

import (
	"context"
)

const addGenre2Movie = `-- name: AddGenre2Movie :exec
INSERT INTO movies_genres(movie_id, genre_id)
VALUES (?, ?)
`

type AddGenre2MovieParams struct {
	MovieID int64
	GenreID int64
}

func (q *Queries) AddGenre2Movie(ctx context.Context, arg AddGenre2MovieParams) error {
	_, err := q.db.ExecContext(ctx, addGenre2Movie, arg.MovieID, arg.GenreID)
	return err
}

const deleteGenresOfMovie = `-- name: DeleteGenresOfMovie :exec

DELETE FROM movies_genres WHERE movie_id = ?
`

func (q *Queries) DeleteGenresOfMovie(ctx context.Context, movieID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGenresOfMovie, movieID)
	return err
}
