// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: watchlist.sql

package repositories

import (
	"context"
)

const addProject2Watchlist = `-- name: AddProject2Watchlist :exec
INSERT INTO watchlist(user_id, project_id)
VALUES (?, ?)
`

type AddProject2WatchlistParams struct {
	UserID    int64
	ProjectID int64
}

func (q *Queries) AddProject2Watchlist(ctx context.Context, arg AddProject2WatchlistParams) error {
	_, err := q.db.ExecContext(ctx, addProject2Watchlist, arg.UserID, arg.ProjectID)
	return err
}

const deleteProjectFromWatchlist = `-- name: DeleteProjectFromWatchlist :exec

DELETE FROM watchlist WHERE user_id = ? AND project_id = ?
`

type DeleteProjectFromWatchlistParams struct {
	UserID    int64
	ProjectID int64
}

func (q *Queries) DeleteProjectFromWatchlist(ctx context.Context, arg DeleteProjectFromWatchlistParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectFromWatchlist, arg.UserID, arg.ProjectID)
	return err
}
