// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: favourites.sql

package database

import (
	"context"
)

const addProject2Favourites = `-- name: AddProject2Favourites :exec
INSERT INTO favourites(user_id, project_id)
VALUES (?, ?)
`

type AddProject2FavouritesParams struct {
	UserID    int64
	ProjectID int64
}

func (q *Queries) AddProject2Favourites(ctx context.Context, arg AddProject2FavouritesParams) error {
	_, err := q.db.ExecContext(ctx, addProject2Favourites, arg.UserID, arg.ProjectID)
	return err
}

const deleteProjectFromFavourites = `-- name: DeleteProjectFromFavourites :exec

DELETE FROM favourites WHERE user_id = ? AND project_id = ?
`

type DeleteProjectFromFavouritesParams struct {
	UserID    int64
	ProjectID int64
}

func (q *Queries) DeleteProjectFromFavourites(ctx context.Context, arg DeleteProjectFromFavouritesParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectFromFavourites, arg.UserID, arg.ProjectID)
	return err
}
