// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type AgeCategory struct {
	ID    int64
	Title string
}

type Favourite struct {
	AddedAt   string
	UserID    int64
	ProjectID int64
}

type Genre struct {
	ID    int64
	Title string
}

type Image struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	ProjectID int64
}

type Permission struct {
	ID    int64
	Title string
}

type Project struct {
	ID             int64
	CreatedAt      string
	UpdatedAt      string
	Title          string
	Description    string
	TypeID         int64
	DurationInMins int64
	ReleaseYear    int64
	Director       string
	Producer       string
	Cover          sql.NullString
	Keywords       string
}

type ProjectsAgeCategory struct {
	ProjectID     int64
	AgeCategoryID int64
}

type ProjectsGenre struct {
	ProjectID int64
	GenreID   int64
}

type RefreshToken struct {
	Token     string
	CreatedAt string
	UpdatedAt string
	UserID    int64
	ExpiresAt string
	RevokedAt sql.NullString
}

type Role struct {
	ID            int64
	Title         string
	Projects      int64
	Genres        int64
	AgeCategories int64
	Types         int64
	Users         int64
	Roles         int64
}

type Type struct {
	ID    int64
	Title string
}

type User struct {
	ID           int64
	CreatedAt    string
	UpdatedAt    string
	Name         string
	Email        string
	PasswordHash string
	DateOfBirth  string
	Phone        string
}

type UsersRole struct {
	AddedAt string
	UserID  int64
	RoleID  int64
}

type Video struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	ProjectID int64
	Season    int64
	Serie     int64
}

type Watchlist struct {
	AddedAt   string
	UserID    int64
	ProjectID int64
}
