// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: projects_genres.sql

package database

import (
	"context"
)

const addGenre2Project = `-- name: AddGenre2Project :exec
INSERT INTO projects_genres(project_id, genre_id)
VALUES (?, ?)
`

type AddGenre2ProjectParams struct {
	ProjectID int64
	GenreID   int64
}

func (q *Queries) AddGenre2Project(ctx context.Context, arg AddGenre2ProjectParams) error {
	_, err := q.db.ExecContext(ctx, addGenre2Project, arg.ProjectID, arg.GenreID)
	return err
}

const deleteGenresOfProject = `-- name: DeleteGenresOfProject :exec

DELETE FROM projects_genres WHERE project_id = ?
`

func (q *Queries) DeleteGenresOfProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGenresOfProject, projectID)
	return err
}
