// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: projects_age_categories.sql

package database

import (
	"context"
)

const addAgeCategory2Project = `-- name: AddAgeCategory2Project :exec
INSERT INTO projects_age_categories(project_id, age_category_id)
VALUES (?, ?)
`

type AddAgeCategory2ProjectParams struct {
	ProjectID     int64
	AgeCategoryID int64
}

func (q *Queries) AddAgeCategory2Project(ctx context.Context, arg AddAgeCategory2ProjectParams) error {
	_, err := q.db.ExecContext(ctx, addAgeCategory2Project, arg.ProjectID, arg.AgeCategoryID)
	return err
}

const deleteAgeCategoriesOfProject = `-- name: DeleteAgeCategoriesOfProject :exec

DELETE FROM projects_age_categories WHERE project_id = ?
`

func (q *Queries) DeleteAgeCategoriesOfProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAgeCategoriesOfProject, projectID)
	return err
}
