// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: roles.sql

package database

import (
	"context"
)

const createRole = `-- name: CreateRole :one

INSERT INTO roles(title, projects, genres, age_categories, types, users, roles)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateRoleParams struct {
	Title         string
	Projects      int64
	Genres        int64
	AgeCategories int64
	Types         int64
	Users         int64
	Roles         int64
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createRole,
		arg.Title,
		arg.Projects,
		arg.Genres,
		arg.AgeCategories,
		arg.Types,
		arg.Users,
		arg.Roles,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteRole = `-- name: DeleteRole :exec

DELETE FROM roles WHERE id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getRoleById = `-- name: GetRoleById :one

SELECT id, title, projects, genres, age_categories, types, users, roles FROM roles WHERE id = ?
`

func (q *Queries) GetRoleById(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleById, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Projects,
		&i.Genres,
		&i.AgeCategories,
		&i.Types,
		&i.Users,
		&i.Roles,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT id, title, projects, genres, age_categories, types, users, roles FROM roles
`

func (q *Queries) GetRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Projects,
			&i.Genres,
			&i.AgeCategories,
			&i.Types,
			&i.Users,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesOfUser = `-- name: GetRolesOfUser :many

SELECT r.id, r.title, r.projects, r.genres, r.age_categories, r.types, r.users, r.roles
FROM roles AS r
JOIN users_roles AS ur
ON r.id = ur.role_id
WHERE ur.user_id = ?
`

func (q *Queries) GetRolesOfUser(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Projects,
			&i.Genres,
			&i.AgeCategories,
			&i.Types,
			&i.Users,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec

UPDATE roles 
SET title = ?,
    projects = ?,
    genres = ?,
    age_categories = ?,
    types = ?,
    users = ?,
    roles = ?
WHERE id = ?
`

type UpdateRoleParams struct {
	Title         string
	Projects      int64
	Genres        int64
	AgeCategories int64
	Types         int64
	Users         int64
	Roles         int64
	ID            int64
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole,
		arg.Title,
		arg.Projects,
		arg.Genres,
		arg.AgeCategories,
		arg.Types,
		arg.Users,
		arg.Roles,
		arg.ID,
	)
	return err
}
